### ISSUE TITLE
Style the login page similar to the home page

### ISSUE THREAD

**Issue by bryanmontalvan** [jakecorrenti/yoru#1]
The current login page form is pretty basic (purposely)
So your goal is change the `/src/css/login.css` to match the same design as the home page
## What does this mean?:
- Change color of background
- Change background transparency
- Make borders(edges) rounded
- Change size and look of buttons

![image](https://user-images.githubusercontent.com/68972382/133349462-968761bf-345d-48bd-8aa5-4734201ee7a4.png)

**Comment by jpope15** [comment]
dan you can change the colors of the buttons and the username/passwords fields

**Comment by bryanmontalvan** [comment]
- Make `Try Now` and `Learn More` button:hover text color orange to offset new background color
- Modify inputs to go along with theme
